### ISSUE TITLE
feat: 유저 면접 종료 화면(면접자)

### ISSUE THREAD

**Issue by KKamjangE** [krafton-jungle-AI-InterviewMate/AI-InterviewMate-FE#102]
### 기능 요약
- 유저 면접 종료 화면 구현

### 참고 자료
![image](https://user-images.githubusercontent.com/105330204/221488125-c26a171d-4bc5-47b6-8fd4-71914590bd0a.png)

**Comment by ahnanne** [comment]
구현되어 있으므로 close
